export type BankMapInfo = {
  id: string;
  name: string;
  city: string;
  address: string;
  rates: string[];
  longitude: string;
  latitude: string;
};

export const BANK_MAP_INFO: BankMapInfo[] = [
  {
    id: '36',
    name: 'Головной офис',
    city: 'Минск',
    address: 'ул. Краснозвездная, 18',
    rates: ['BHD', 'BRL', 'BYN', 'CAD', 'CHF', 'ETH', 'GBP', 'LTC'],
    longitude: '27.590875',
    latitude: '53.907836',
  },
  {
    id: '41',
    name: 'Центр банковских услуг №700',
    city: 'Минск',
    address: 'пр-т Независимости, 58 (ТЦ Московско-Венский).',
    rates: ['AUD', 'BHD', 'BTC', 'CHF', 'ETH', 'GBP', 'USD'],
    longitude: '27.589141',
    latitude: '53.917830',
  },
  {
    id: '104',
    name: 'Центр банковских услуг №702',
    city: 'Минск',
    address: 'ул. Притыцкого, 89, пом. 5 Н',
    rates: ['BTC', 'BYN', 'CAD', 'ETH', 'EUR', 'JPY'],
    longitude: '27.445912',
    latitude: '53.905827',
  },
  {
    id: '78',
    name: 'Центр банковских услуг №100',
    city: 'Брест',
    address: 'ул. Пушкинская, 18-15',
    rates: ['BYN', 'CHF', 'CNY', 'GBP', 'LTC', 'RUB'],
    longitude: '23.688781',
    latitude: '52.095734',
  },
  {
    id: '102',
    name: 'Пункт обмена валют №1',
    city: 'Минск',
    address: 'ул. Тимирязева, 74 А (ТЦ Palazzo)',
    rates: ['BRL', 'CAD', 'EUR', 'USD'],
    longitude: '27.509846',
    latitude: '53.927029',
  },
  {
    id: '63',
    name: 'Центр банковских услуг № 200',
    city: 'Витебск',
    address: 'пр-т Московский, 8',
    rates: ['AUD', 'BRL', 'CNY', 'RUB', 'USD'],
    longitude: '30.206247',
    latitude: '55.183395',
  },
  {
    id: '144',
    name: 'Пункт обмена валют №1 Центра банковских услуг №200',
    city: 'Витебск',
    address: 'ул. Ленина, 26а (ТРК Марко-Сити)',
    rates: ['BRL', 'BTC', 'CAD', 'CHF', 'ETH', 'EUR'],
    longitude: '30.203812',
    latitude: '55.191269',
  },
  {
    id: '145',
    name: 'Пункт обмена валют №2 Центра банковских услуг №200',
    city: 'Витебск',
    address: 'пр-т Строителей, 15Г (ТЦ Трио)',
    rates: ['AUD', 'CAD'],
    longitude: '30.217988',
    latitude: '55.170511',
  },
  {
    id: '110',
    name: 'Центр банковских услуг №101',
    city: 'Брест',
    address: 'Варшавское шоссе, 11-1 (ТЦ Евроопт)',
    rates: ['BRL', 'CAD', 'CHF', 'ETH', 'RUB'],
    longitude: '23.717976',
    latitude: '52.075419',
  },
  {
    id: '112',
    name: 'Пункт обмена валют №3 Центра банковских услуг №200',
    city: 'Витебск',
    address: 'ул. Строителей, 15-1 (ТЦ Евроопт)',
    rates: ['BHD', 'BRL', 'BTC', 'BYN', 'ETH', 'GBP', 'USD', 'JPY'],
    longitude: '30.223099',
    latitude: '55.169961',
  },
  {
    id: '113',
    name: 'Пункт обмена валют №4 Центра банковских услуг №200',
    city: 'Витебск',
    address: 'пр-т Московский 130-1 (ТЦ Евроопт)',
    rates: ['AUD', 'BTC', 'CNY', 'ETH', 'JPY'],
    longitude: '30.267404',
    latitude: '55.173787',
  },
  {
    id: '59',
    name: 'Центр банковских услуг №300',
    city: 'Гомель',
    address: 'пр. Ленина, 35',
    rates: ['AUD', 'BHD', 'BTC', 'BYN', 'CAD', 'CHF', 'CNY', 'RUB', 'USD'],
    longitude: '31.002909',
    latitude: '52.427691',
  },
  {
    id: '84',
    name: 'Пункт обмена валют №1 Центра банковских услуг №300',
    city: 'Гомель',
    address: 'пр. Речицкий, 40 (рынок Давыдовский)',
    rates: ['AUD', 'BTC', 'BYN', 'GBP', 'LTC', 'RUB'],
    longitude: '30.936020',
    latitude: '52.408352',
  },
  {
    id: '87',
    name: 'Пункт обмена валют №2 Центра банковских услуг №300',
    city: 'Гомель',
    address: 'ул. Огоренко, 33 (ТЦ Волотовской)',
    rates: ['BHD', 'CAD', 'EUR', 'USD'],
    longitude: '31.022555',
    latitude: '52.468851',
  },
  {
    id: '57',
    name: 'Центр банковских услуг №400',
    city: 'Гродно',
    address: 'ул. Большая Троицкая, 17-3',
    rates: ['BHD', 'BRL', 'BTC', 'CAD', 'CHF', 'USD', 'JPY'],
    longitude: '23.829502',
    latitude: '53.681946',
  },
  {
    id: '131',
    name: 'Центр банковских услуг №600',
    city: 'Могилев',
    address: 'ул. Первомайская, 9-60А',
    rates: ['BTC', 'CHF', 'ETH', 'EUR', 'USD', 'JPY'],
    longitude: '30.333313',
    latitude: '53.898358',
  },
  {
    id: '153',
    name: 'Пункт обмена валют №1 Центра банковских услуг №600',
    city: 'Могилев',
    address: 'ул. Гагарина, 79 (ТЦ Евроопт)',
    rates: ['BHD', 'BTC', 'CAD', 'CHF', 'EUR', 'LTC', 'RUB', 'USD'],
    longitude: '30.317350',
    latitude: '53.880130',
  },
  {
    id: '147',
    name: 'Пункт обмена валют №1 Центра банковских услуг №400',
    city: 'Гродно',
    address: 'ул. Тимирязева, 8 (ТЦ Евроопт)',
    rates: ['BRL', 'BYN', 'CAD', 'EUR', 'USD', 'JPY'],
    longitude: '23.845402',
    latitude: '53.688670',
  },
  {
    id: '148',
    name: 'Пункт обмена валют №2 Центра банковских услуг №400',
    city: 'Гродно',
    address: 'ул. Огинского, 12 (ТЦ Парус)',
    rates: ['BTC', 'CHF', 'LTC', 'RUB', 'JPY'],
    longitude: '23.815964',
    latitude: '53.618253',
  },
  {
    id: '152',
    name: 'Пункт обмена валют №3 центра банковских услуг №400',
    city: 'Гродно',
    address: 'ул. Кабяка, 13, (ТЦ Алми)',
    rates: ['AUD', 'BHD', 'BTC', 'CAD', 'CNY', 'ETH', 'EUR', 'USD'],
    longitude: '23.851205',
    latitude: '53.643381',
  },
  {
    id: '151',
    name: 'Пункт обмена валют №4 центра банковских услуг №400',
    city: 'Гродно',
    address: 'ул. Советская, 18',
    rates: ['BTC', 'BYN', 'CHF', 'LTC', 'USD', 'JPY'],
    longitude: '23.831541',
    latitude: '53.682346',
  },
  {
    id: '120',
    name: 'Центр банковских услуг №501',
    city: 'Борисов',
    address: 'ул. Гагарина, 107-2 (ТЦ Евроопт)',
    rates: ['BHD', 'CAD', 'CHF', 'GBP', 'USD'],
    longitude: '28.486171',
    latitude: '54.206648',
  },
  {
    id: '55',
    name: 'Центр банковских услуг №603',
    city: 'Бобруйск',
    address: 'ул. Социалистическая, 63',
    rates: ['BHD', 'BYN', 'CHF', 'EUR', 'JPY'],
    longitude: '29.227406',
    latitude: '53.131957',
  },
  {
    id: '150',
    name: 'Пункт обмена валют №1 Центра банковских услуг №603',
    city: 'Бобруйск',
    address: 'пр-т Строителей, 58 (ТРЦ Спектр)',
    rates: ['AUD', 'BHD', 'BRL', 'BYN', 'CNY', 'ETH', 'EUR', 'LTC'],
    longitude: '29.223957',
    latitude: '53.195058',
  },
  {
    id: '157',
    name: 'Пункт обмена валют №2 Центра банковских услуг №603',
    city: 'Бобруйск',
    address: 'ул. Минская, 111 (ТЦ Евроопт)',
    rates: ['AUD', 'BHD', 'BRL', 'BTC', 'EUR', 'GBP', 'RUB'],
    longitude: '29.207060',
    latitude: '53.165393',
  },
  {
    id: '159',
    name: 'Пункт обмена валют №2 Центра банковских услуг №600',
    city: 'Могилев',
    address: 'Минское шоссе, 31, (ТЦ ПАРК-СИТИ)',
    rates: ['AUD', 'BRL', 'BTC', 'CAD', 'CHF', 'ETH', 'GBP', 'USD', 'JPY'],
    longitude: '30.257639',
    latitude: '53.935644',
  },
  {
    id: '146',
    name: 'Пункт обмена валют №3 Центра банковских услуг №300',
    city: 'Гомель',
    address: 'ул. Хатаевича, 9 (ТЦ Евроопт)',
    rates: ['BHD', 'BTC', 'BYN', 'EUR', 'GBP', 'RUB', 'JPY'],
    longitude: '31.016473',
    latitude: '52.445337',
  },
  {
    id: '123',
    name: 'Пункт обмена валют №2',
    city: 'Минск',
    address: 'ул. Нестерова, 49 (ТЦ Евроопт)',
    rates: ['CAD', 'ETH', 'EUR', 'GBP', 'LTC'],
    longitude: '27.681424',
    latitude: '53.883601',
  },
  {
    id: '124',
    name: 'Пункт обмена валют №3',
    city: 'Минск',
    address: 'пр. Дзержинского, 104 - 110 (ТЦ Евроопт)',
    rates: ['AUD', 'BHD', 'CAD', 'CHF', 'CNY', 'USD', 'JPY'],
    longitude: '27.480390',
    latitude: '53.861867',
  },
  {
    id: '125',
    name: 'Пункт обмена валют №4',
    city: 'Минск',
    address: 'ул. Одинцова, 65 (ТЦ Гиппо)',
    rates: ['AUD', 'BHD', 'BRL', 'CHF', 'ETH', 'EUR', 'GBP', 'RUB'],
    longitude: '27.441304',
    latitude: '53.899950',
  },
  {
    id: '126',
    name: 'Пункт обмена валют №5',
    city: 'Минск',
    address: 'ул. И. Гошкевича, 3-2 (ТЦ Евроопт)',
    rates: ['BHD', 'BYN', 'CAD', 'CNY', 'LTC', 'USD', 'JPY'],
    longitude: '27.568784',
    latitude: '53.840143',
  },
  {
    id: '127',
    name: 'Пункт обмена валют №6',
    city: 'Минск',
    address: 'ул. Налибокская, 1-1 (ТЦ Караван)',
    rates: ['BHD', 'BYN', 'CNY', 'GBP', 'LTC', 'USD', 'JPY'],
    longitude: '27.440172',
    latitude: '53.926499',
  },
  {
    id: '128',
    name: 'Пункт обмена валют №7',
    city: 'Минск',
    address: 'ул. Денисовская, 8-2 (ТЦ Корона-Сити)',
    rates: ['BRL', 'BYN', 'CAD', 'CHF', 'CNY', 'LTC', 'RUB'],
    longitude: '27.572799',
    latitude: '53.871594',
  },
  {
    id: '129',
    name: 'Пункт обмена валют №8',
    city: 'Минск',
    address: 'ул. Денисовская, 8-2 (ТЦ Корона-Сити)',
    rates: ['AUD', 'BYN', 'CNY', 'ETH', 'EUR', 'LTC', 'RUB'],
    longitude: '27.572799',
    latitude: '53.871594',
  },
  {
    id: '138',
    name: 'Пункт обмена валют №1 Центра банковских услуг №100',
    city: 'Брест',
    address: 'ул. Московская, 328 (ТЦ Алми)',
    rates: ['AUD', 'BHD', 'BTC', 'CAD', 'ETH', 'LTC', 'USD', 'JPY'],
    longitude: '23.758661',
    latitude: '52.099552',
  },
  {
    id: '137',
    name: 'Пункт обмена валют №4 Центра банковских услуг №300',
    city: 'Гомель',
    address: 'Гомель, пр. Речицкий, 5В, (ТРЦ Мандарин Плаза).',
    rates: ['AUD', 'BHD', 'BYN', 'CAD', 'GBP', 'RUB'],
    longitude: '30.923911',
    latitude: '52.405605',
  },
  {
    id: '142',
    name: 'Пункт обмена валют №10',
    city: 'Минск',
    address: 'пр-т Дзержинского, 91, (ТЦ Алми)',
    rates: ['BHD', 'BRL', 'CAD', 'ETH', 'GBP'],
    longitude: '27.481926',
    latitude: '53.859557',
  },
  {
    id: '154',
    name: 'Пункт обмена валют №5 Центра банковских услуг №400',
    city: 'Гродно',
    address: 'ул. Я. Купалы, 82А (ТЦ Евроопт)',
    rates: ['BHD', 'BRL', 'CAD', 'CHF', 'ETH', 'LTC', 'RUB', 'JPY'],
    longitude: '23.852930',
    latitude: '53.652652',
  },
  {
    id: '155',
    name: 'Пункт обмена валют №6 Центра банковских услуг №400',
    city: 'Гродно',
    address: 'ул. Ольги Соломовой, 112, (ТЦ Алми)',
    rates: ['AUD', 'EUR', 'GBP', 'RUB', 'USD', 'JPY'],
    longitude: '23.781011',
    latitude: '53.656489',
  },
  {
    id: '160',
    name: 'Пункт обмена валют №11',
    city: 'Минск',
    address: 'ул. Городецкая, 30, (ТЦ Гиппо)',
    rates: ['CNY', 'USD'],
    longitude: '27.678109',
    latitude: '53.947420',
  },
  {
    id: '161',
    name: 'Пункт обмена валют №12',
    city: 'Минск',
    address: 'ул. Макаёнка, 11, (ТЦ Виталюр).',
    rates: ['AUD', 'CHF', 'RUB', 'JPY'],
    longitude: '27.628244',
    latitude: '53.921340',
  },
  {
    id: '162',
    name: 'Пункт обмена валют №2 Центра банковских услуг №100',
    city: 'Брест',
    address: 'ул. Махновича, 6 (ТЦ Варшавский)',
    rates: ['AUD', 'BYN', 'CAD', 'CHF', 'ETH', 'LTC', 'RUB', 'USD', 'JPY'],
    longitude: '23.706693',
    latitude: '52.073006',
  },
  {
    id: '163',
    name: 'Пункт обмена валют №13',
    city: 'Минск',
    address: 'ул. Толстого, 1 (ТЦ Minsk City Mall)',
    rates: ['AUD', 'BRL', 'ETH', 'EUR', 'RUB', 'USD'],
    longitude: '27.545230',
    latitude: '53.889529',
  },
  {
    id: '164',
    name: 'Пункт обмена валют №14',
    city: 'Минск',
    address: 'ул. Горецкого, 2 (ТЦ Гиппо)',
    rates: ['AUD', 'BHD', 'BRL', 'CHF', 'ETH', 'USD'],
    longitude: '27.466080',
    latitude: '53.876515',
  },
  {
    id: '165',
    name: 'Пункт обмена валют №3 Центра банковских услуг №100',
    city: 'Брест',
    address: 'пр-т Машерова, 17 (ЦУМ)',
    rates: ['BHD', 'CHF', 'CNY', 'ETH', 'LTC', 'RUB'],
    longitude: '23.694754',
    latitude: '52.085354',
  },
  {
    id: '166',
    name: 'Пункт обмена валют № 15',
    city: 'Минск',
    address: 'Минский район, Щомыслицкий сельсовет, 32, корпус 4 (ТЦ DiaMond city)',
    rates: ['AUD', 'BTC', 'BYN', 'CHF', 'CNY', 'GBP', 'LTC', 'RUB', 'JPY'],
    longitude: '27.433570',
    latitude: '53.849610',
  },
  {
    id: '167',
    name: 'Пункт обмена валют № 16',
    city: 'Минск',
    address: 'Минск, ул. Кальварийская, 24 (ТЦ Корона)',
    rates: ['BYN', 'CHF', 'ETH', 'EUR', 'GBP', 'USD'],
    longitude: '27.527327',
    latitude: '53.908039',
  },
  {
    id: '168',
    name: 'Пункт обмена валют №4 Центра банковских услуг №100',
    city: 'Брест',
    address: 'ул. Карьерная, 9Б (ТЦ Mile)',
    rates: ['BTC', 'CAD', 'CHF', 'ETH', 'LTC', 'RUB', 'USD'],
    longitude: '23.756298',
    latitude: '52.063998',
  },
  {
    id: '169',
    name: 'Пункт обмена валют №17',
    city: 'Минск',
    address: 'ул. Петра Глебки, 5-1 (ТЦ Скала)',
    rates: ['AUD', 'BRL', 'CAD', 'CHF', 'JPY'],
    longitude: '27.470185',
    latitude: '53.908851',
  },
  {
    id: '170',
    name: 'Пункт обмена валют №5 Центра банковских услуг №100',
    city: 'Брест',
    address: 'ул. Московская, 210 (ТЦ Корона)',
    rates: ['BYN', 'CAD', 'ETH', 'EUR', 'GBP', 'LTC', 'RUB', 'USD', 'JPY'],
    longitude: '23.744674',
    latitude: '52.097212',
  },
  {
    id: '172',
    name: 'Пункт обмена валют № 18',
    city: 'Минск',
    address: 'Минск, ул. Веры Хоружей, 8 (Комаровский рынок)',
    rates: ['BHD', 'BTC', 'BYN', 'CNY', 'EUR', 'GBP', 'LTC', 'RUB'],
    longitude: '27.577381',
    latitude: '53.919770',
  },
];
