name: Lint
on: [push]
jobs:
  eslint:
    name: Lint
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: Pretty
        uses: borales/actions-yarn@v4
        with:
          cmd: pretty
